#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ]; do
    ls=$(ls -ld "$PRG")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=$(dirname "$PRG")/"$link"
    fi
done
SAVED="$(pwd)"
cd "$(dirname "$PRG")/" >/dev/null
APP_HOME="$(pwd -P)"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

OS_NAME=$(uname -s)
case "$OS_NAME" in
    CYGWIN* | MINGW* | MSYS* )
        IS_WINDOWS=true
        ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Try to find Java: check JAVA_HOME, then common locations, then PATH
if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
elif [ -x /usr/lib/jvm/default/bin/java ]; then
    JAVACMD="/usr/lib/jvm/default/bin/java"
elif [ -x /usr/lib/jvm/default-runtime/bin/java ]; then
    JAVACMD="/usr/lib/jvm/default-runtime/bin/java"
else
    JAVACMD="java"
fi

if [ ! -x "$JAVACMD" ]; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set JAVA_HOME to your JDK installation, e.g.:
  export JAVA_HOME=/usr/lib/jvm/java-21-openjdk"
fi

GRADLE_OPTS="${GRADLE_OPTS} -Dorg.gradle.appname=${APP_BASE_NAME}"

exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
